### ISSUE TITLE
初始化数据库表结构SQL语句有Bug

### ISSUE THREAD

**Issue by xgsong** [dongxuyang1985/postgresql_dev_guide#1]
修改后的SQL语句：ALTER TABLE departments ADD CONSTRAINT dept_mgr_fk FOREIGN KEY ( manager_id ) REFERENCES employees ( employee_id );

environment：PostgreSQL 14.3 (Debian 14.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**Comment by dongxuyang1985** [comment]
已经调整了，谢谢！
